singleuser:
  image:
    name: "docker.io/htdang/immad"
    tag: "newly-build"
    pullPolicy: IfNotPresent
  cmd:
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "notebook.notebookapp.NotebookApp"
  storage:
    dynamic:
      storageClass: nfs-client
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", 'echo Hello, world! > /home/jovyan/message']
  initContainers:
    - name: initialize-user
      image: htdang/init-user:newly-build
      command: ['/bin/sh']
      args: ['/immad/init.sh', '{unescaped_username}', 'PSQL_PASSWORD', '/var/immad', 'RABBITMQ_USER', 'RABBITMQ_PASSWORD']
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: immad-config
        mountPath: /var/immad
  storage:
    extraVolumes:
    - name: immad-config
      emptyDir: {}
    - name: share
      nfs:
        server: HOSTNAME
        path: /state/partition1/share
    extraVolumeMounts:
    - name: immad-config
      mountPath: /var/immad
    - name: share
      mountPath: /srv/share

imagePullSecrets:
  - name: immad-cred

cull:
    enabled: true
  # timeout = 24h
    timeout: 86400
  # check every hour
    every: 3600

hub:
  networkPolicy:
    enabled: false
  livenessProbe:
    enabled: false
    initialDelaySeconds: 60
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
  config:
    GoogleOAuthenticator:
      client_id: GOOGLE_CLIENT_ID
      client_secret: GOOGLE_CLIENT_SECRET
      oauth_callback_url: https://HOSTNAME/hub/oauth_callback
      hosted_domain:
        - gmail.com
      login_service: Google
    JupyterHub:
      authenticator_class: google
    Authenticator:
      allow_existing_users: true
      admin_users:
        - someone@somewhere
  extraConfig:
    timeout_config.py: |
      c.KubeSpawner.http_timeout = 300

prePuller:
  hook:
    enabled: false
